
# ⬇️  Change this to match the URL of your Outerbounds deployment
platform = 'dev-yellow.outerbounds.xyz'

# ⬇️  Change these to match your project name
project = 'product-images-demo'
title = 'Generate Product Images from Snowflake Data'

# (optional) disable automatic application of a project-wide pyproject.toml
# [dependencies]
# include_pyproject_toml=false

# (optional) Enable this section to access assets in local runs
# [dev-assets]
# branch = 'dev'
# read-only = true
